/-
The atoms of a probability space.

A σ-algebra on the countable set `ℕ` is generated by its atoms: the atom of `n` is the
intersection of the events containing `n`, and it is itself an event (a countable
intersection suffices).  A probability space is therefore the sum of its atoms
(`ProbSpace.le_sum_atoms`, `ProbSpace.sum_atoms_le`), each of which carries no probabilistic
information: all its events have probability `0` or `1`.
-/
import PcolIris.OProp.SumLaws

namespace Pcol

open MeasureTheory

namespace ProbSpace

variable (p : ProbSpace)

/-- The atom of `n`: the intersection of the events containing `n`. -/
def atom (n : ℕ) : Set ℕ := ⋂₀ {E | p.mspace.MeasurableSet' E ∧ n ∈ E}

variable {p}

lemma mem_atom (n : ℕ) : n ∈ p.atom n := fun _ hE ↦ hE.2

lemma atom_subset {E : Set ℕ} (hE : E ∈ p) {n : ℕ} (hn : n ∈ E) : p.atom n ⊆ E :=
  Set.sInter_subset_of_mem ⟨hE, hn⟩

lemma atom_measurable (n : ℕ) : p.atom n ∈ p := by
  classical
  have h : ∀ m : {m // m ∉ p.atom n}, ∃ E, p.mspace.MeasurableSet' E ∧ n ∈ E ∧ m.1 ∉ E := by
    intro ⟨m, hm⟩
    simp only [atom, Set.mem_sInter, Set.mem_setOf_eq, not_forall] at hm
    obtain ⟨E, ⟨hE, hn⟩, hmE⟩ := hm
    exact ⟨E, hE, hn, hmE⟩
  choose E hE hnE hmE using h
  have heq : p.atom n = ⋂ m, E m := by
    ext x
    refine ⟨fun hx ↦ Set.mem_iInter.mpr fun m ↦ atom_subset (hE m) (hnE m) hx, fun hx ↦ ?_⟩
    by_contra hx'
    exact hmE ⟨x, hx'⟩ (Set.mem_iInter.mp hx ⟨x, hx'⟩)
  rw [heq]
  exact @MeasurableSet.iInter ℕ _ p.mspace _ _ hE

/-- An event contains an atom or misses it. -/
lemma atom_subset_or_disjoint {E : Set ℕ} (hE : E ∈ p) (n : ℕ) :
    p.atom n ⊆ E ∨ Disjoint (p.atom n) E := by
  by_cases hn : n ∈ E
  · exact Or.inl (atom_subset hE hn)
  · refine Or.inr (Set.disjoint_left.mpr fun m hm hmE ↦ ?_)
    exact atom_subset (p := p) (@MeasurableSet.compl ℕ E p.mspace hE) hn hm hmE

/-- Points of the same atom have the same atom. -/
lemma atom_eq_of_mem {n m : ℕ} (h : m ∈ p.atom n) : p.atom m = p.atom n := by
  apply Set.Subset.antisymm
  · exact atom_subset (atom_measurable n) h
  · rcases atom_subset_or_disjoint (atom_measurable m) n with h' | h'
    · exact h'
    · exact absurd (mem_atom m) (Set.disjoint_left.mp h' h)

lemma atom_disjoint {n m : ℕ} (h : p.atom n ≠ p.atom m) : Disjoint (p.atom n) (p.atom m) := by
  refine Set.disjoint_left.mpr fun x hxn hxm ↦ h ?_
  rw [← atom_eq_of_mem hxn, atom_eq_of_mem hxm]

/-! ### The space of an atom -/

/-- The σ-algebra of the events that contain the set `A` or miss it. -/
@[reducible] def atomMSpace (A : Set ℕ) : MeasurableSpace ℕ where
  MeasurableSet' E := A ⊆ E ∨ Disjoint A E
  measurableSet_empty := Or.inr (Set.disjoint_empty _)
  measurableSet_compl E h := h.elim (fun h ↦ Or.inr (Set.disjoint_compl_right_iff_subset.mpr h))
    (fun h ↦ Or.inl (Set.subset_compl_iff_disjoint_right.mpr h))
  measurableSet_iUnion f hf := by
    by_cases h : ∃ i, A ⊆ f i
    · obtain ⟨i, hi⟩ := h
      exact Or.inl (hi.trans (Set.subset_iUnion f i))
    · push Not at h
      exact Or.inr (Set.disjoint_iUnion_right.mpr fun i ↦ (hf i).resolve_left (h i))

/-- The space of the atom `A ∋ a` of `p`: all the probability is on `A`, and no event
distinguishes its points. -/
noncomputable def atomSpace (A : Set ℕ) (a : ℕ) (ha : a ∈ A) : ProbSpace where
  mspace := atomMSpace A
  μ := ⟨@Measure.dirac ℕ (atomMSpace A) a, @Measure.dirac.isProbabilityMeasure ℕ (atomMSpace A) a⟩
  dom := p.dom
  state := p.state
  dom_valid := p.dom_valid
  complete := by
    constructor
    intro s hs
    obtain ⟨t, hst, ht, ht0⟩ :=
      @exists_measurable_superset_of_null ℕ (atomMSpace A) _ s hs
    change @Measure.dirac ℕ (atomMSpace A) a t = 0 at ht0
    rcases ht with ht | ht
    · rw [@Measure.dirac_apply' ℕ (atomMSpace A) t a (Or.inl ht),
        Set.indicator_of_mem (ht ha)] at ht0
      exact absurd ht0 one_ne_zero
    · exact Or.inr (ht.mono_right hst)

variable {A : Set ℕ} {a : ℕ} {ha : a ∈ A}

open Classical in
lemma atomSpace_meas {E : Set ℕ} (hE : E ∈ p.atomSpace A a ha) :
    (p.atomSpace A a ha).meas E = if A ⊆ E then 1 else 0 := by
  change @Measure.dirac ℕ (atomMSpace A) a E = _
  rw [@Measure.dirac_apply' ℕ (atomMSpace A) E a hE]
  rcases hE with hE | hE
  · rw [if_pos hE, Set.indicator_of_mem (hE ha)]; rfl
  · rw [Set.indicator_of_notMem (Set.disjoint_left.mp hE ha), if_neg]
    intro h; exact Set.disjoint_left.mp hE ha (h ha)

lemma support_atomSpace : (p.atomSpace A a ha).support = A := by
  apply Set.Subset.antisymm
  · refine support_subset (Or.inl subset_rfl) ?_
    change (p.atomSpace A a ha).meas A = 1
    rw [atomSpace_meas (Or.inl subset_rfl), if_pos subset_rfl]
  · intro x hx
    rw [support_eq, Set.mem_sInter]
    rintro E ⟨hE, h1⟩
    rcases hE with hE | hE
    · exact hE hx
    · change (p.atomSpace A a ha).meas E = 1 at h1
      rw [atomSpace_meas (Or.inr hE), if_neg] at h1
      · exact absurd h1 zero_ne_one
      · intro h; exact Set.disjoint_left.mp hE ha (h ha)

/-- All events of an atom have probability `0` or `1`. -/
lemma atomSpace_zero_one {E : Set ℕ} (hE : E ∈ p.atomSpace A a ha) :
    (p.atomSpace A a ha).μ E = 0 ∨ (p.atomSpace A a ha).μ E = 1 := by
  have h := atomSpace_meas hE
  have hc := prob_coe (p.atomSpace A a ha).μ E
  change _ = (p.atomSpace A a ha).meas E at hc
  rw [h] at hc
  split_ifs at hc
  · right; exact_mod_cast hc
  · left; exact_mod_cast hc

/-! ### A space is the sum of its atoms -/

variable (p)

/-- The atoms of `p`. -/
abbrev Atoms : Type := Set.range p.atom

instance : Countable p.Atoms := (Set.countable_range _).to_subtype

variable {p}

/-- A point of an atom. -/
noncomputable def Atoms.pt (A : p.Atoms) : ℕ := A.2.choose

lemma Atoms.atom_pt (A : p.Atoms) : p.atom A.pt = A.1 := A.2.choose_spec

lemma Atoms.pt_mem (A : p.Atoms) : A.pt ∈ A.1 := by
  rw [← A.atom_pt]; exact mem_atom _

lemma Atoms.measurable (A : p.Atoms) : A.1 ∈ p := by
  rw [← A.atom_pt]; exact atom_measurable _

lemma Atoms.disjoint {A B : p.Atoms} (h : A ≠ B) : Disjoint A.1 B.1 := by
  rw [← A.atom_pt, ← B.atom_pt]
  refine atom_disjoint fun h' ↦ h (Subtype.ext ?_)
  rw [← A.atom_pt, ← B.atom_pt, h']

/-- The atom of a point, as an element of `p.Atoms`. -/
def Atoms.of (p : ProbSpace) (n : ℕ) : p.Atoms := ⟨p.atom n, n, rfl⟩

lemma Atoms.mem_of (n : ℕ) : n ∈ (Atoms.of p n).1 := mem_atom n

lemma Atoms.subset_or_disjoint (A : p.Atoms) {E : Set ℕ} (hE : E ∈ p) :
    A.1 ⊆ E ∨ Disjoint A.1 E := by
  rw [← A.atom_pt]; exact atom_subset_or_disjoint hE _

variable (p)

/-- The probabilities of the atoms. -/
noncomputable def atomWeights : PMF p.Atoms := ⟨fun A ↦ p.meas A.1, by
  rw [ENNReal.summable.hasSum_iff,
    ← measure_iUnion (m0 := p.mspace) (μ := p.meas) (f := fun (B : p.Atoms) ↦ B.1)
      (fun A B h ↦ Atoms.disjoint h) (fun A ↦ Atoms.measurable A)]
  have : (⋃ A : p.Atoms, A.1) = Set.univ :=
    Set.eq_univ_of_forall fun n ↦ Set.mem_iUnion.mpr ⟨Atoms.of p n, Atoms.mem_of n⟩
  rw [this]
  exact @measure_univ ℕ p.mspace p.meas p.μ.2⟩

/-- The spaces of the atoms. -/
noncomputable def atomSpaces (A : p.Atoms) : ProbSpace := p.atomSpace A.1 A.pt A.pt_mem

variable {p}

lemma atomSpaces_disjoint {A B : p.Atoms} (h : A ≠ B) :
    Disjoint (p.atomSpaces A).support (p.atomSpaces B).support := by
  rw [atomSpaces, atomSpaces, support_atomSpace, support_atomSpace]
  exact Atoms.disjoint h

variable (p)

/-- The sum of the atoms of `p`, which is `p` itself. -/
noncomputable def sumAtoms : ProbSpace :=
  sum p.atomWeights p.atomSpaces p.dom atomSpaces_disjoint (fun _ ↦ rfl)

variable {p}

lemma mem_sumAtoms_iff {E : Set ℕ} : E ∈ p.sumAtoms ↔ E ∈ p := by
  constructor
  · intro hE
    -- The atoms of probability zero form a null event
    set N := ⋃ A : {A : p.Atoms // p.atomWeights A = 0}, A.1.1 with hN
    have hNm : N ∈ p := @MeasurableSet.iUnion ℕ _ p.mspace _ _ fun A ↦ A.1.measurable
    have hN0 : p.meas N = 0 :=
      measure_iUnion_null fun A ↦ A.2
    set P := ⋃ A : {A : p.Atoms // p.atomWeights A ≠ 0 ∧ A.1 ⊆ E}, A.1.1
    have hPm : P ∈ p := @MeasurableSet.iUnion ℕ _ p.mspace _ _ fun A ↦ A.1.measurable
    have hEN : E ∩ N ∈ p := p.complete.out _ (measure_mono_null Set.inter_subset_right hN0)
    have heq : E = P ∪ (E ∩ N) := by
      apply Set.Subset.antisymm
      · intro x hx
        by_cases hw : p.atomWeights (Atoms.of p x) = 0
        · exact Or.inr ⟨hx, Set.mem_iUnion.mpr ⟨⟨_, hw⟩, Atoms.mem_of x⟩⟩
        · have h := hE (Atoms.of p x) hw
          change (Atoms.of p x).1 ⊆ E ∩ (p.atomSpaces _).support ∨
            Disjoint (Atoms.of p x).1 (E ∩ (p.atomSpaces _).support) at h
          rw [atomSpaces, support_atomSpace] at h
          rcases h with h | h
          · exact Or.inl (Set.mem_iUnion.mpr ⟨⟨_, hw, fun y hy ↦ (h hy).1⟩, Atoms.mem_of x⟩)
          · exact absurd ⟨hx, Atoms.mem_of x⟩ (Set.disjoint_left.mp h (Atoms.mem_of x))
      · refine Set.union_subset ?_ Set.inter_subset_left
        intro x hx
        obtain ⟨A, hA⟩ := Set.mem_iUnion.mp hx
        exact A.2.2 hA
    rw [heq]
    exact @MeasurableSet.union ℕ p.mspace _ _ hPm hEN
  · intro hE A _
    change A.1 ⊆ E ∩ (p.atomSpaces A).support ∨ Disjoint A.1 (E ∩ (p.atomSpaces A).support)
    rw [atomSpaces, support_atomSpace]
    rcases A.subset_or_disjoint hE with h | h
    · exact Or.inl (Set.subset_inter h subset_rfl)
    · exact Or.inr (h.mono_right Set.inter_subset_left)

lemma sumAtoms_meas {E : Set ℕ} (hE : E ∈ p) : p.sumAtoms.meas E = p.meas E := by
  classical
  change sumMeasure p.atomWeights p.atomSpaces E = _
  rw [sumMeasure_apply _ _ (mem_sumAtoms_iff.mpr hE), sumMeasureFun]
  have hsplit : p.meas E = ∑' A : p.Atoms, p.meas (E ∩ A.1) := by
    rw [← measure_iUnion (m0 := p.mspace) (μ := p.meas) (f := fun (B : p.Atoms) ↦ E ∩ B.1)
      (fun A B h ↦ (Atoms.disjoint h).mono Set.inter_subset_right Set.inter_subset_right)
      (fun A ↦ @MeasurableSet.inter ℕ p.mspace _ _ hE A.measurable)]
    congr 1
    ext x
    simp only [Set.mem_iUnion, Set.mem_inter_iff]
    exact ⟨fun hx ↦ ⟨Atoms.of p x, hx, Atoms.mem_of x⟩, fun ⟨_, hx, _⟩ ↦ hx⟩
  rw [hsplit]
  refine tsum_congr fun A ↦ ?_
  have hsupp : (p.atomSpaces A).support = A.1 := support_atomSpace
  rw [hsupp]
  change p.meas A.1 * (p.atomSpace A.1 A.pt A.pt_mem).meas (E ∩ A.1) = _
  rcases A.subset_or_disjoint hE with h | h
  · rw [atomSpace_meas (Or.inl (Set.subset_inter h subset_rfl)),
      if_pos (Set.subset_inter h subset_rfl), mul_one, Set.inter_eq_right.mpr h]
  · have hEA : E ∩ A.1 = ∅ := h.symm.inter_eq
    rw [hEA, measure_empty, measure_empty, mul_zero]

lemma sumAtoms_state (n : ℕ) : p.sumAtoms.state n = p.state n := by
  change sumState p.atomSpaces p.dom n = _
  rw [sumState_of_mem atomSpaces_disjoint (v := Atoms.of p n)]
  · rfl
  · rw [atomSpaces, support_atomSpace]; exact Atoms.mem_of n

/-- A space carries no more information than the sum of its atoms. -/
theorem le_sumAtoms (p : ProbSpace) : p ≤ p.sumAtoms :=
  le_of_id (fun _ h ↦ mem_sumAtoms_iff.mpr h) (fun E hE ↦ by
      refine ENNReal.coe_injective ?_
      rw [prob_coe, prob_coe]; exact (sumAtoms_meas hE).symm)
    subset_rfl (fun n _ ↦ le_of_eq (sumAtoms_state n).symm)

/-- The sum of the atoms of a space carries no more information than the space. -/
theorem sumAtoms_le (p : ProbSpace) : p.sumAtoms ≤ p :=
  le_of_id (fun _ h ↦ mem_sumAtoms_iff.mp h) (fun E hE ↦ by
      refine ENNReal.coe_injective ?_
      rw [prob_coe, prob_coe]; exact sumAtoms_meas (mem_sumAtoms_iff.mp hE))
    subset_rfl (fun n _ ↦ le_of_eq (sumAtoms_state n))

end ProbSpace

end Pcol
